server:
  port: 8150
  tomcat:
    max-swallow-size: -1
  servlet:
    multipart:
      max-file-size:
      location: /src/main/resources/static/uploaded
    context-path: /food-orders


upload:
  dir: /uploadImages

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_orders
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connectionTimeout: 10000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mail:
    host: maildev
    port: 1025
    username: admin
    password: admin
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

api:
  spoonacular:
    url: https://api.spoonacular.com/
    apiKey: YOUR_NEW_API_KEY_HERE


springdoc:
  api-docs:
    path: /developer/api-docs
  swagger-ui:
    path: /developer/swagger-ui-custom.html